version: '2'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: lein test
  format:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: clojure -A:lint:lint/fix
